name = "pe-youtube-filter"
main = "worker/index.js"
compatibility_date = "2024-09-23"

[triggers]
crons = ["0 9 * * *"]  # runs daily at 9:00 UTC

[[d1_databases]]
binding     = "DB"
database_name = "pe-reports"
database_id   = "6e7f5302-47ab-42db-a2af-7fbf5e268347"
